---
branches:
  - "main"
  - name: "alfa"
    prerelease: true
  - name: "beta"
    prerelease: true
  - name: "develop"
    prerelease: true

tagFormat: v${version}

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/exec"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"

verifyConditions:
  - '@semantic-release/git'
analyzeCommits:
  - path: "@semantic-release/commit-analyzer"
    preset: "conventionalcommits"

    releaseRules:
      - type: "docs"
        release: "patch"
      - type: "feat"
        release: "minor"
      - type: "fix"
        release: "patch"
#       - type: "fix"
#         release: "patch"
#       - type: "patch"
#         release: "patch"
#       - type: "minor"
#         release: "minor"
#       - type: "breaking"
#         release: "major"
generateNotes:
  - path: "@semantic-release/release-notes-generator"
    preset: "conventionalcommits"
    # linkCompare: true
    # linkReferences: true
    #  parserOpts
    #   noteKeywords
    #     - feat
    #     - fix 
    #     - doc 
    # writerOpts:
    #   groupBy: "type"
    #   commitGroupsSort:
    #     - "feat"
    #     - "fix"
    #     - "docs"
    # commitsSort: "header"
#     types:
#       - type: "feat"
#       - section: "Features"
#       # Tracked bug fix with a hotfix branch
#       - type: "hotfix"
#       - section: "Bug Fixes"
#       # Uninmportent fix (CI testing, etc)
#       - type: "fix"
#       - hidden: true
#       - type: "chore"
#       - hidden: true
#       - type: "docs"
#       - section: "Documentation"
#       - type: "doc"
#       - hidden: true
#       - type: "style"
#       - hidden: true
#       - type: "refactor"
#       - hidden: true
#       - type: "perf"
#       - hidden: true
#       - type: "test"
#       - hidden: true
#     presetConfig: true

prepare:
  - path: "@semantic-release/changelog"
    changelogFile: "CHANGELOG.md"

  - path: "@semantic-release/git"
    assets: "CHANGELOG.md"
publish:
  - path: "@semantic-release/github"
    assets: "CHANGELOG.md"
  - path: "@semantic-release/exec"
    publishCmd: "echo ${nextRelease.version} > VERSION.txt"